In [268]:
from google.colab import files #Import Library

uploaded = files.upload() #Uploaded Named  varibable files.upload is command Inbuilt function

Saving spotify_raw_data.csv to spotify_raw_data (7).csv

In [269]:
import pandas as pd

In [270]:
df = pd.read_csv("spotify_raw_data.csv") #df is data frame ,  csv  comma seperated  values

In [271]:
df

,track_id,track_name,artist_name,genre,popularity,duration_ms,explicit,danceability,energy,tempo,release_date
0,3n3Pp770487xV,HUMBLE.,Dua Lipa,Rap,97,230821,True,0.765,0.400,124.7,2025-01-10
1,3n3Pp216739xV,Umbrella,The Weeknd,Hip-Hop,72,271463,False,0.582,0.866,123.6,2016-05-12
2,3n3Pp126225xV,Sugar,Kendrick Lamar,Rap,53,219470,False,0.561,0.496,76.5,2019-06-23
3,3n3Pp877572xV,Blinding Lights,Dua Lipa,EDM,56,181434,False,0.923,0.533,120.0,2021-04-11
4,3n3Pp388389xV,One Dance,Justin Bieber,EDM,77,173703,true,0.740,0.847,166.6,2015-03-02
...,...,...,...,...,...,...,...,...,...,...,...
1025,3n3Pp658582xV,NaN,Billie Eilish,Hip-Hop,82,169661,False,0.683,0.636,118.5,2022
1026,3n3Pp765822xV,NaN,Post Malone,Rap,60,223644,False,0.447,0.399,94.8,2015-09-23
1027,3n3Pp437960xV,NaN,Ariana Grande,Hip-Hop,56,207661,No,0.592,0.817,143.0,2016-07-21
1028,3n3Pp328552xV,NaN,Coldplay,EDM,97,297398,True,0.681,0.704,162.7,2018
1029,3n3Pp464069xV,NaN,Doja Cat,Rock,64,203238,True,0.484,0.371,84.7,2016-05-14

In [272]:
df["track_id"].duplicated().sum()

np.int64(30)

In [273]:
df[df["track_id"].duplicated()]

,track_id,track_name,artist_name,genre,popularity,duration_ms,explicit,danceability,energy,tempo,release_date
1000,3n3Pp423232xV,NaN,Maroon 5,Rap,76,unknown,False,0.648,0.394,137.1,2015-10-12
1001,3n3Pp227253xV,NaN,The Weeknd,Hip-Hop,50,177187,False,0.598,0.711,172.3,2015-12-08
1002,3n3Pp940346xV,NaN,Justin Bieber,Rap,52,299145,False,0.935,0.741,171.4,2019-01-11
1003,3n3Pp100425xV,NaN,Doja Cat,Rap,90,220772,False,0.702,0.461,116.7,2015-12-06
1004,3n3Pp712024xV,NaN,Post Malone,Hip-Hop,60,285074,False,0.721,0.443,154.9,2020-12-01
1005,3n3Pp934692xV,NaN,Ed Sheeran,Hip-Hop,70,192040,No,0.548,0.480,159.6,2017-07-27
1006,3n3Pp552248xV,NaN,drake,Rock,57,155013,True,0.879,0.690,163.8,2021
1007,3n3Pp975136xV,NaN,Taylor Swift,Hip-Hop,93,159258,True,0.927,0.707,126.5,2022-12-10
1008,3n3Pp152727xV,NaN,Rihanna,K-Pop,59,280764,True,0.821,0.730,149.6,2024-08-21
1009,3n3Pp774079xV,NaN,Rihanna,Hip-Hop,88,164724,True,0.484,0.946,134.6,2025-06-05
1010,3n3Pp498858xV,NaN,Dua Lipa,Pop,60,283257,False,0.577,0.872,96.7,2018
1011,3n3Pp793384xV,NaN,Post Malone,Indie,100,223341,False,0.555,0.690,152.4,2022-02-16
1012,3n3Pp414910xV,NaN,BTS,Rock,56,159794,True,0.639,0.477,107.6,2021-03-01
1013,3n3Pp782054xV,NaN,Ed Sheeran,Rap,94,272245,Yes,0.533,0.421,84.5,2015-09-07
1014,3n3Pp991597xV,NaN,Post Malone,NaN,65,unknown,True,0.911,0.409,158.7,2019-10-13
1015,3n3Pp801978xV,NaN,Drake,Rock,86,234510,True,0.919,0.305,111.7,2019-05-20
1016,3n3Pp132938xV,NaN,Post Malone,R&B,69,230832,True,0.907,0.443,125.5,2021-01-18
1017,3n3Pp781725xV,NaN,Dua Lipa,K-Pop,83,186223,True,0.703,0.418,94.8,2025-08-13
1018,3n3Pp371782xV,NaN,Post Malone,R&B,55,286078,True,0.596,0.853,149.9,2022-02-01
1019,3n3Pp939482xV,NaN,The Weeknd,Rock,63,228342,Yes,0.821,0.473,104.5,2021-02-07
1020,3n3Pp531712xV,NaN,Coldplay,Rap,54,273789,No,0.861,0.301,144.1,2020-07-19
1021,3n3Pp680099xV,NaN,Drake,Reggaeton,94,230431,true,0.760,0.826,172.4,2023-12-27
1022,3n3Pp262316xV,NaN,Doja Cat,Rap,76,277293,False,0.730,0.553,76.1,2015-03-22
1023,3n3Pp815198xV,NaN,Doja Cat,Rock,99,175586,True,NaN,0.608,137.0,2023-03-25
1024,3n3Pp269396xV,NaN,post malone,Rap,55,260009,False,0.757,0.409,177.5,2017-11-15
1025,3n3Pp658582xV,NaN,Billie Eilish,Hip-Hop,82,169661,False,0.683,0.636,118.5,2022
1026,3n3Pp765822xV,NaN,Post Malone,Rap,60,223644,False,0.447,0.399,94.8,2015-09-23
1027,3n3Pp437960xV,NaN,Ariana Grande,Hip-Hop,56,207661,No,0.592,0.817,143.0,2016-07-21
1028,3n3Pp328552xV,NaN,Coldplay,EDM,97,297398,True,0.681,0.704,162.7,2018
1029,3n3Pp464069xV,NaN,Doja Cat,Rock,64,203238,True,0.484,0.371,84.7,2016-05-14

In [274]:
df.count() #we can check the data completeness

track_id        1030
track_name       970
artist_name     1000
genre            999
popularity      1030
duration_ms     1030
explicit        1030
danceability     999
energy          1030
tempo           1030
release_date    1030
dtype: int64

In [275]:
df = df.drop_duplicates(subset=["track_id"], keep="first") #subset means which columns pandas should use , keep first keeps first entry drops other

In [276]:
df["track_id"].duplicated().sum()

np.int64(0)

In [277]:
df.count()

track_id        1000
track_name       970
artist_name      970
genre            970
popularity      1000
duration_ms     1000
explicit        1000
danceability     970
energy          1000
tempo           1000
release_date    1000
dtype: int64

In [278]:
df['track_name'].isna().sum() #isna is is null

np.int64(30)

In [279]:
df=df.dropna(subset=['track_name'])

In [280]:
df.count()

track_id        970
track_name      970
artist_name     940
genre           941
popularity      970
duration_ms     970
explicit        970
danceability    941
energy          970
tempo           970
release_date    970
dtype: int64

In [281]:
df['artist_name'].isna().sum()

np.int64(30)

In [282]:
df = df.dropna(subset=["artist_name"])

In [283]:
df.count()

track_id        940
track_name      940
artist_name     940
genre           912
popularity      940
duration_ms     940
explicit        940
danceability    912
energy          940
tempo           940
release_date    940
dtype: int64

In [284]:
df["genre"].isna().sum()

np.int64(28)

In [285]:
df['genre'] = df['genre'].fillna('Unknown') #fill na is used to fill the null values

In [286]:
df.count()

track_id        940
track_name      940
artist_name     940
genre           940
popularity      940
duration_ms     940
explicit        940
danceability    912
energy          940
tempo           940
release_date    940
dtype: int64

In [287]:
df['popularity'] = pd.to_numeric(df["popularity"], errors="coerce") #coerce is to convert text to numbers without errors

In [288]:
df

,track_id,track_name,artist_name,genre,popularity,duration_ms,explicit,danceability,energy,tempo,release_date
0,3n3Pp770487xV,HUMBLE.,Dua Lipa,Rap,97.0,230821,True,0.765,0.400,124.7,2025-01-10
1,3n3Pp216739xV,Umbrella,The Weeknd,Hip-Hop,72.0,271463,False,0.582,0.866,123.6,2016-05-12
2,3n3Pp126225xV,Sugar,Kendrick Lamar,Rap,53.0,219470,False,0.561,0.496,76.5,2019-06-23
3,3n3Pp877572xV,Blinding Lights,Dua Lipa,EDM,56.0,181434,False,0.923,0.533,120.0,2021-04-11
4,3n3Pp388389xV,One Dance,Justin Bieber,EDM,77.0,173703,true,0.740,0.847,166.6,2015-03-02
...,...,...,...,...,...,...,...,...,...,...,...
995,3n3Pp587282xV,Levitating,Ed Sheeran,Pop,84.0,255753,False,0.801,0.456,101.1,2020-07-17
996,3n3Pp697530xV,7 rings,Taylor Swift,K-Pop,72.0,174102,False,0.447,0.580,119.9,2015
997,3n3Pp739979xV,Shape of You,Post Malone,Reggaeton,99.0,241593,False,0.807,0.655,134.7,2022-04-04
998,3n3Pp800646xV,One Dance,Kendrick Lamar,Reggaeton,63.0,207985,True,0.534,0.886,132.9,2019-11-19
999,3n3Pp497399xV,Bléeding Love,Ed Sheeran,R&B,78.0,205929,False,0.742,0.447,171.3,2022-07-10

In [289]:
df['popularity'].isna().sum()

np.int64(19)

In [290]:
df['popularity'] = df['popularity'].fillna(df['popularity'].median()) #median is avg value

In [291]:
df

,track_id,track_name,artist_name,genre,popularity,duration_ms,explicit,danceability,energy,tempo,release_date
0,3n3Pp770487xV,HUMBLE.,Dua Lipa,Rap,97.0,230821,True,0.765,0.400,124.7,2025-01-10
1,3n3Pp216739xV,Umbrella,The Weeknd,Hip-Hop,72.0,271463,False,0.582,0.866,123.6,2016-05-12
2,3n3Pp126225xV,Sugar,Kendrick Lamar,Rap,53.0,219470,False,0.561,0.496,76.5,2019-06-23
3,3n3Pp877572xV,Blinding Lights,Dua Lipa,EDM,56.0,181434,False,0.923,0.533,120.0,2021-04-11
4,3n3Pp388389xV,One Dance,Justin Bieber,EDM,77.0,173703,true,0.740,0.847,166.6,2015-03-02
...,...,...,...,...,...,...,...,...,...,...,...
995,3n3Pp587282xV,Levitating,Ed Sheeran,Pop,84.0,255753,False,0.801,0.456,101.1,2020-07-17
996,3n3Pp697530xV,7 rings,Taylor Swift,K-Pop,72.0,174102,False,0.447,0.580,119.9,2015
997,3n3Pp739979xV,Shape of You,Post Malone,Reggaeton,99.0,241593,False,0.807,0.655,134.7,2022-04-04
998,3n3Pp800646xV,One Dance,Kendrick Lamar,Reggaeton,63.0,207985,True,0.534,0.886,132.9,2019-11-19
999,3n3Pp497399xV,Bléeding Love,Ed Sheeran,R&B,78.0,205929,False,0.742,0.447,171.3,2022-07-10

In [292]:
df['duration_ms'] = pd.to_numeric(df['duration_ms'],errors="coerce")

In [293]:
df['duration_ms'].isna().sum()

np.int64(18)

In [294]:
df['duration_ms'] = df['duration_ms'].fillna(df['duration_ms'].median())

In [295]:
df

,track_id,track_name,artist_name,genre,popularity,duration_ms,explicit,danceability,energy,tempo,release_date
0,3n3Pp770487xV,HUMBLE.,Dua Lipa,Rap,97.0,230821.0,True,0.765,0.400,124.7,2025-01-10
1,3n3Pp216739xV,Umbrella,The Weeknd,Hip-Hop,72.0,271463.0,False,0.582,0.866,123.6,2016-05-12
2,3n3Pp126225xV,Sugar,Kendrick Lamar,Rap,53.0,219470.0,False,0.561,0.496,76.5,2019-06-23
3,3n3Pp877572xV,Blinding Lights,Dua Lipa,EDM,56.0,181434.0,False,0.923,0.533,120.0,2021-04-11
4,3n3Pp388389xV,One Dance,Justin Bieber,EDM,77.0,173703.0,true,0.740,0.847,166.6,2015-03-02
...,...,...,...,...,...,...,...,...,...,...,...
995,3n3Pp587282xV,Levitating,Ed Sheeran,Pop,84.0,255753.0,False,0.801,0.456,101.1,2020-07-17
996,3n3Pp697530xV,7 rings,Taylor Swift,K-Pop,72.0,174102.0,False,0.447,0.580,119.9,2015
997,3n3Pp739979xV,Shape of You,Post Malone,Reggaeton,99.0,241593.0,False,0.807,0.655,134.7,2022-04-04
998,3n3Pp800646xV,One Dance,Kendrick Lamar,Reggaeton,63.0,207985.0,True,0.534,0.886,132.9,2019-11-19
999,3n3Pp497399xV,Bléeding Love,Ed Sheeran,R&B,78.0,205929.0,False,0.742,0.447,171.3,2022-07-10

In [296]:
df["explicit"] = df["explicit"].replace({
    "True" : "True",
    "False" : "False",
    "true" : "True",
    "false" : "False",
    "TRUE" : "True",
    "FALSE" : "False",
    "Yes":"True",
    "No":"False",
    "yes":"True",
    "no":"False"
})

In [297]:
df

,track_id,track_name,artist_name,genre,popularity,duration_ms,explicit,danceability,energy,tempo,release_date
0,3n3Pp770487xV,HUMBLE.,Dua Lipa,Rap,97.0,230821.0,True,0.765,0.400,124.7,2025-01-10
1,3n3Pp216739xV,Umbrella,The Weeknd,Hip-Hop,72.0,271463.0,False,0.582,0.866,123.6,2016-05-12
2,3n3Pp126225xV,Sugar,Kendrick Lamar,Rap,53.0,219470.0,False,0.561,0.496,76.5,2019-06-23
3,3n3Pp877572xV,Blinding Lights,Dua Lipa,EDM,56.0,181434.0,False,0.923,0.533,120.0,2021-04-11
4,3n3Pp388389xV,One Dance,Justin Bieber,EDM,77.0,173703.0,True,0.740,0.847,166.6,2015-03-02
...,...,...,...,...,...,...,...,...,...,...,...
995,3n3Pp587282xV,Levitating,Ed Sheeran,Pop,84.0,255753.0,False,0.801,0.456,101.1,2020-07-17
996,3n3Pp697530xV,7 rings,Taylor Swift,K-Pop,72.0,174102.0,False,0.447,0.580,119.9,2015
997,3n3Pp739979xV,Shape of You,Post Malone,Reggaeton,99.0,241593.0,False,0.807,0.655,134.7,2022-04-04
998,3n3Pp800646xV,One Dance,Kendrick Lamar,Reggaeton,63.0,207985.0,True,0.534,0.886,132.9,2019-11-19
999,3n3Pp497399xV,Bléeding Love,Ed Sheeran,R&B,78.0,205929.0,False,0.742,0.447,171.3,2022-07-10

In [298]:
df['danceability'].isna().sum()

np.int64(28)

In [299]:
df['danceability']=df['danceability'].fillna(df['danceability'].median())

In [300]:
df

,track_id,track_name,artist_name,genre,popularity,duration_ms,explicit,danceability,energy,tempo,release_date
0,3n3Pp770487xV,HUMBLE.,Dua Lipa,Rap,97.0,230821.0,True,0.765,0.400,124.7,2025-01-10
1,3n3Pp216739xV,Umbrella,The Weeknd,Hip-Hop,72.0,271463.0,False,0.582,0.866,123.6,2016-05-12
2,3n3Pp126225xV,Sugar,Kendrick Lamar,Rap,53.0,219470.0,False,0.561,0.496,76.5,2019-06-23
3,3n3Pp877572xV,Blinding Lights,Dua Lipa,EDM,56.0,181434.0,False,0.923,0.533,120.0,2021-04-11
4,3n3Pp388389xV,One Dance,Justin Bieber,EDM,77.0,173703.0,True,0.740,0.847,166.6,2015-03-02
...,...,...,...,...,...,...,...,...,...,...,...
995,3n3Pp587282xV,Levitating,Ed Sheeran,Pop,84.0,255753.0,False,0.801,0.456,101.1,2020-07-17
996,3n3Pp697530xV,7 rings,Taylor Swift,K-Pop,72.0,174102.0,False,0.447,0.580,119.9,2015
997,3n3Pp739979xV,Shape of You,Post Malone,Reggaeton,99.0,241593.0,False,0.807,0.655,134.7,2022-04-04
998,3n3Pp800646xV,One Dance,Kendrick Lamar,Reggaeton,63.0,207985.0,True,0.534,0.886,132.9,2019-11-19
999,3n3Pp497399xV,Bléeding Love,Ed Sheeran,R&B,78.0,205929.0,False,0.742,0.447,171.3,2022-07-10

In [301]:
df['danceability'].isna().sum()

np.int64(0)

In [302]:
df.count()

track_id        940
track_name      940
artist_name     940
genre           940
popularity      940
duration_ms     940
explicit        940
danceability    940
energy          940
tempo           940
release_date    940
dtype: int64

In [303]:
df['energy'].isna().sum()

np.int64(0)

In [304]:
df['tempo'].isna().sum()

np.int64(0)

In [305]:
df["release_date"] = pd.to_datetime(df["release_date"], errors="coerce")
# to_datetime Converttext into actual date format that Panda can understand
# error... if the value cant be converted to date then it is converted to NAT(Not a time),#coerce is to convert text to numbers without errors

In [306]:
df

,track_id,track_name,artist_name,genre,popularity,duration_ms,explicit,danceability,energy,tempo,release_date
0,3n3Pp770487xV,HUMBLE.,Dua Lipa,Rap,97.0,230821.0,True,0.765,0.400,124.7,2025-01-10
1,3n3Pp216739xV,Umbrella,The Weeknd,Hip-Hop,72.0,271463.0,False,0.582,0.866,123.6,2016-05-12
2,3n3Pp126225xV,Sugar,Kendrick Lamar,Rap,53.0,219470.0,False,0.561,0.496,76.5,2019-06-23
3,3n3Pp877572xV,Blinding Lights,Dua Lipa,EDM,56.0,181434.0,False,0.923,0.533,120.0,2021-04-11
4,3n3Pp388389xV,One Dance,Justin Bieber,EDM,77.0,173703.0,True,0.740,0.847,166.6,2015-03-02
...,...,...,...,...,...,...,...,...,...,...,...
995,3n3Pp587282xV,Levitating,Ed Sheeran,Pop,84.0,255753.0,False,0.801,0.456,101.1,2020-07-17
996,3n3Pp697530xV,7 rings,Taylor Swift,K-Pop,72.0,174102.0,False,0.447,0.580,119.9,NaT
997,3n3Pp739979xV,Shape of You,Post Malone,Reggaeton,99.0,241593.0,False,0.807,0.655,134.7,2022-04-04
998,3n3Pp800646xV,One Dance,Kendrick Lamar,Reggaeton,63.0,207985.0,True,0.534,0.886,132.9,2019-11-19
999,3n3Pp497399xV,Bléeding Love,Ed Sheeran,R&B,78.0,205929.0,False,0.742,0.447,171.3,2022-07-10

In [307]:
df["release_year"]= df["release_date"].dt.year
#dt is date time acesssor
#converts to float instead of int
#and converts nat to nan

In [308]:
df

,track_id,track_name,artist_name,genre,popularity,duration_ms,explicit,danceability,energy,tempo,release_date,release_year
0,3n3Pp770487xV,HUMBLE.,Dua Lipa,Rap,97.0,230821.0,True,0.765,0.400,124.7,2025-01-10,2025.0
1,3n3Pp216739xV,Umbrella,The Weeknd,Hip-Hop,72.0,271463.0,False,0.582,0.866,123.6,2016-05-12,2016.0
2,3n3Pp126225xV,Sugar,Kendrick Lamar,Rap,53.0,219470.0,False,0.561,0.496,76.5,2019-06-23,2019.0
3,3n3Pp877572xV,Blinding Lights,Dua Lipa,EDM,56.0,181434.0,False,0.923,0.533,120.0,2021-04-11,2021.0
4,3n3Pp388389xV,One Dance,Justin Bieber,EDM,77.0,173703.0,True,0.740,0.847,166.6,2015-03-02,2015.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,3n3Pp587282xV,Levitating,Ed Sheeran,Pop,84.0,255753.0,False,0.801,0.456,101.1,2020-07-17,2020.0
996,3n3Pp697530xV,7 rings,Taylor Swift,K-Pop,72.0,174102.0,False,0.447,0.580,119.9,NaT,NaN
997,3n3Pp739979xV,Shape of You,Post Malone,Reggaeton,99.0,241593.0,False,0.807,0.655,134.7,2022-04-04,2022.0
998,3n3Pp800646xV,One Dance,Kendrick Lamar,Reggaeton,63.0,207985.0,True,0.534,0.886,132.9,2019-11-19,2019.0
999,3n3Pp497399xV,Bléeding Love,Ed Sheeran,R&B,78.0,205929.0,False,0.742,0.447,171.3,2022-07-10,2022.0

In [309]:
df['release_year'].isna().sum()

np.int64(53)

In [310]:
df["release_year"]= df["release_year"].fillna(df["release_year"].mode()[0]).astype(int)

In [311]:
df

,track_id,track_name,artist_name,genre,popularity,duration_ms,explicit,danceability,energy,tempo,release_date,release_year
0,3n3Pp770487xV,HUMBLE.,Dua Lipa,Rap,97.0,230821.0,True,0.765,0.400,124.7,2025-01-10,2025
1,3n3Pp216739xV,Umbrella,The Weeknd,Hip-Hop,72.0,271463.0,False,0.582,0.866,123.6,2016-05-12,2016
2,3n3Pp126225xV,Sugar,Kendrick Lamar,Rap,53.0,219470.0,False,0.561,0.496,76.5,2019-06-23,2019
3,3n3Pp877572xV,Blinding Lights,Dua Lipa,EDM,56.0,181434.0,False,0.923,0.533,120.0,2021-04-11,2021
4,3n3Pp388389xV,One Dance,Justin Bieber,EDM,77.0,173703.0,True,0.740,0.847,166.6,2015-03-02,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
995,3n3Pp587282xV,Levitating,Ed Sheeran,Pop,84.0,255753.0,False,0.801,0.456,101.1,2020-07-17,2020
996,3n3Pp697530xV,7 rings,Taylor Swift,K-Pop,72.0,174102.0,False,0.447,0.580,119.9,NaT,2020
997,3n3Pp739979xV,Shape of You,Post Malone,Reggaeton,99.0,241593.0,False,0.807,0.655,134.7,2022-04-04,2022
998,3n3Pp800646xV,One Dance,Kendrick Lamar,Reggaeton,63.0,207985.0,True,0.534,0.886,132.9,2019-11-19,2019
999,3n3Pp497399xV,Bléeding Love,Ed Sheeran,R&B,78.0,205929.0,False,0.742,0.447,171.3,2022-07-10,2022

In [312]:
df=df.drop(columns="release_date")

In [313]:
df

,track_id,track_name,artist_name,genre,popularity,duration_ms,explicit,danceability,energy,tempo,release_year
0,3n3Pp770487xV,HUMBLE.,Dua Lipa,Rap,97.0,230821.0,True,0.765,0.400,124.7,2025
1,3n3Pp216739xV,Umbrella,The Weeknd,Hip-Hop,72.0,271463.0,False,0.582,0.866,123.6,2016
2,3n3Pp126225xV,Sugar,Kendrick Lamar,Rap,53.0,219470.0,False,0.561,0.496,76.5,2019
3,3n3Pp877572xV,Blinding Lights,Dua Lipa,EDM,56.0,181434.0,False,0.923,0.533,120.0,2021
4,3n3Pp388389xV,One Dance,Justin Bieber,EDM,77.0,173703.0,True,0.740,0.847,166.6,2015
...,...,...,...,...,...,...,...,...,...,...,...
995,3n3Pp587282xV,Levitating,Ed Sheeran,Pop,84.0,255753.0,False,0.801,0.456,101.1,2020
996,3n3Pp697530xV,7 rings,Taylor Swift,K-Pop,72.0,174102.0,False,0.447,0.580,119.9,2020
997,3n3Pp739979xV,Shape of You,Post Malone,Reggaeton,99.0,241593.0,False,0.807,0.655,134.7,2022
998,3n3Pp800646xV,One Dance,Kendrick Lamar,Reggaeton,63.0,207985.0,True,0.534,0.886,132.9,2019
999,3n3Pp497399xV,Bléeding Love,Ed Sheeran,R&B,78.0,205929.0,False,0.742,0.447,171.3,2022

In [314]:
(df["popularity"]<0).sum()

np.int64(10)

In [315]:
import numpy as np

In [319]:
df.loc[df["popularity"] < 0, "popularity"] = np.nan

In [320]:
df["popularity"] = df["popularity"].fillna(df["popularity"].median())

In [321]:
df

,track_id,track_name,artist_name,genre,popularity,duration_ms,explicit,danceability,energy,tempo,release_year
0,3n3Pp770487xV,HUMBLE.,Dua Lipa,Rap,97.0,230821.0,True,0.765,0.400,124.7,2025
1,3n3Pp216739xV,Umbrella,The Weeknd,Hip-Hop,72.0,271463.0,False,0.582,0.866,123.6,2016
2,3n3Pp126225xV,Sugar,Kendrick Lamar,Rap,53.0,219470.0,False,0.561,0.496,76.5,2019
3,3n3Pp877572xV,Blinding Lights,Dua Lipa,EDM,56.0,181434.0,False,0.923,0.533,120.0,2021
4,3n3Pp388389xV,One Dance,Justin Bieber,EDM,77.0,173703.0,True,0.740,0.847,166.6,2015
...,...,...,...,...,...,...,...,...,...,...,...
995,3n3Pp587282xV,Levitating,Ed Sheeran,Pop,84.0,255753.0,False,0.801,0.456,101.1,2020
996,3n3Pp697530xV,7 rings,Taylor Swift,K-Pop,72.0,174102.0,False,0.447,0.580,119.9,2020
997,3n3Pp739979xV,Shape of You,Post Malone,Reggaeton,99.0,241593.0,False,0.807,0.655,134.7,2022
998,3n3Pp800646xV,One Dance,Kendrick Lamar,Reggaeton,63.0,207985.0,True,0.534,0.886,132.9,2019
999,3n3Pp497399xV,Bléeding Love,Ed Sheeran,R&B,78.0,205929.0,False,0.742,0.447,171.3,2022

In [324]:
(df['duration_ms']< 0) .sum()

np.int64(0)

In [325]:
(df['danceability']<0).sum()

np.int64(0)

In [326]:
(df['tempo']<0).sum()

np.int64(0)

In [328]:
(df["energy"]<0).sum()

np.int64(0)

In [329]:
df.to_csv("SPOTIFY_CLEANED")